/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.Receptionist;

import controllers.PatientController;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.OptionPaneUI;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author Chashika
 */
public class PatientDischarge extends javax.swing.JFrame {

    /**
     * Creates new form PatientDischarge
     */
    JOptionPane frame = new JOptionPane();
    public PatientDischarge() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtMedicineCost = new javax.swing.JTextField();
        choosDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Discharge", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        jPanel1.setLayout(null);

        jLabel2.setText("Patient ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 75, 68, 14);

        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 122, 48, 14);

        jLabel4.setText("Medicine cost");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 178, 78, 14);

        jLabel5.setText("Discharge Date");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 229, 94, 14);
        jPanel1.add(txtPID);
        txtPID.setBounds(116, 68, 75, 29);
        jPanel1.add(txtName);
        txtName.setBounds(96, 115, 151, 29);
        jPanel1.add(txtMedicineCost);
        txtMedicineCost.setBounds(134, 170, 73, 31);

        choosDate.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(choosDate);
        choosDate.setBounds(134, 227, 100, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/mvQmsXm.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 30, 300, 290);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 60, 300, 310);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Discharge & bill >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 190, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/medical-cross-symbols-against-blue-background1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int patientid = Integer.parseInt(txtPID.getText());
            PatientController pc = new PatientController();
           

            int medicnCharg = Integer.parseInt(txtMedicineCost.getText());
            String DischrgDate = ((JTextField)choosDate.getDateEditor().getUiComponent()).getText();
            
            double bill = pc.paybill(patientid,  medicnCharg, DischrgDate);
            
            double ward = bill-medicnCharg;
            
            UIManager UI=new UIManager();
            UI.put("OptionPane.background", Color.white);
            UI.put("Panel.background", Color.white);
            Font f = new Font("dialog",Font.BOLD,14);
            Font j = new Font("dialog",Font.BOLD,2);
            UIManager.put("Label.font", f);
            UIManager.put("Button.font", f);
            UIManager.put("TitledBorder.font", j);
            UIManager.put("OptionPane.messageFont", new Font("System", Font.PLAIN, 30));
            UIManager.put("OptionPane.buttonFont", new Font("System", Font.PLAIN, 20));
            
            JDialog.setDefaultLookAndFeelDecorated(true);
            Font font = UIManager.getFont("InternalFrame.titleFont");
            UIManager.put("InternalFrame.titleFont",
        new FontUIResource(font.deriveFont(40.0f)));

            String msg = "<html><body bgcolor=\"#CCCCCC\">Patient id = "+patientid +"<br>"
                    + "Name = "+txtName.getText()+"<br>"
                    + "Medicine cost = Rs"+medicnCharg+"<br>"
                    + "Ward Charge = Rs"+ward+"<br><br>"
                    + "<b>Total cost = Rs"+bill+"</b></body></html>";
            JOptionPane optnpane = new JOptionPane();
            optnpane.setMessage(msg);
            optnpane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = optnpane.createDialog(null,"Invoice");
            dialog.setVisible(true);
                    
            
            pc.dischargePatient(patientid);
            
           
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(frame,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDischarge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDischarge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDischarge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDischarge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDischarge().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser choosDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMedicineCost;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPID;
    // End of variables declaration//GEN-END:variables
}
