/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.Receptionist;

import classes.Ward;
import controllers.WardController;
import DatabaseConnection.DbConnect;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Chashika
 */
public class wardInfo extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    
    public wardInfo() {
        initComponents();
        
        con = DbConnect.Connect();
        tableloadStart();
    }
    
    public void tableloadStart(){
        try {
            String sql = "SELECT * FROM ward";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (HeadlessException|SQLException ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtWardID = new javax.swing.JTextField();
        combWardType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCharge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNoOfBeds = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRemainingBeds = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ward Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N
        jPanel1.setLayout(null);

        jLabel2.setText("Ward type");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(16, 74, 51, 14);

        jLabel1.setText("Ward ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(16, 36, 60, 14);
        jPanel1.add(txtWardID);
        txtWardID.setBounds(80, 33, 38, 20);

        combWardType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ward", "Maternity", "Pediatrics", "Oncology", "Gynecologist" }));
        combWardType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combWardTypeActionPerformed(evt);
            }
        });
        jPanel1.add(combWardType);
        combWardType.setBounds(85, 71, 107, 20);

        jLabel3.setText("Charge(Per day)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(16, 129, 100, 14);
        jPanel1.add(txtCharge);
        txtCharge.setBounds(150, 120, 59, 30);

        jLabel4.setText("RS");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 130, 13, 14);

        jLabel5.setText("NoOf beds");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(16, 173, 70, 14);

        txtNoOfBeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOfBedsActionPerformed(evt);
            }
        });
        jPanel1.add(txtNoOfBeds);
        txtNoOfBeds.setBounds(100, 170, 43, 20);

        jLabel6.setText("Remaining beds");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(16, 211, 90, 14);
        jPanel1.add(txtRemainingBeds);
        txtRemainingBeds.setBounds(130, 210, 73, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/mvQmsXm.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 20, 360, 240);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(26, 49, 270, 250);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        btnAdd.setBackground(new java.awt.Color(51, 51, 51));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(51, 51, 51));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(51, 51, 51));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(404, 49, 95, 115);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ward ID", "Ward type", "NoOfBeds", "Charge(Per day)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(26, 323, 399, 141);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/logosmall.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(390, 340, 210, 190);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/images/medical-cross-symbols-against-blue-background1.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -130, 730, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combWardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combWardTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combWardTypeActionPerformed

    private void txtNoOfBedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOfBedsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoOfBedsActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            if (combWardType.getSelectedItem().equals("Select ward")) {
                JOptionPane.showMessageDialog( this, "Please Select a ward type","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtCharge.getText().equals("")){
                JOptionPane.showMessageDialog( this, "Please insert the charge","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtNoOfBeds.getText().equals("")){
                JOptionPane.showMessageDialog( this, "Please insert the No of Beds","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int charg = Integer.parseInt(txtCharge.getText());
            int Noofbeds = Integer.parseInt(txtNoOfBeds.getText());
            int remainBeds = Integer.parseInt(txtRemainingBeds.getText());
            
            Ward W = new Ward((String)combWardType.getSelectedItem(),charg,Noofbeds,remainBeds);
            WardController wc= new WardController();
            wc.createWard(W);
            tableloadStart();
            
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int x = JOptionPane.showConfirmDialog(null,"Do you really want to update this?");
        
        if(x==0){
            int wid = Integer.parseInt(txtWardID.getText());
            int charg = Integer.parseInt(txtCharge.getText());
            int Noofbeds = Integer.parseInt(txtNoOfBeds.getText());
            int remainBeds = Integer.parseInt(txtRemainingBeds.getText());

            Ward W = new Ward((String)combWardType.getSelectedItem(),charg,Noofbeds,remainBeds);
            WardController wc= new WardController();
            wc.updateWard(W,wid);
            tableloadStart();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       try {
            String sql = "SELECT * FROM ward Where WardID='"+txtWardID.getText()+"' OR WType='"+combWardType.getSelectedItem()+"'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (HeadlessException|SQLException ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wardInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wardInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wardInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wardInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wardInfo().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> combWardType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txtCharge;
    private javax.swing.JTextField txtNoOfBeds;
    private javax.swing.JTextField txtRemainingBeds;
    private javax.swing.JTextField txtWardID;
    // End of variables declaration//GEN-END:variables
}
